Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
image = []
for i in range(len(files)):
    image.append(fits.open(directory+'fzt_ALrd'+str(files[i])+'.fits')[0])
for i in range(len(files)):
    print(image[i].header['FILENAME'],image[i].header['OBJECT'],image[i].header['EXPTIME'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-6beccc42b658>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mimage[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mfiles[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m     [0mimage[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mfits[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mdirectory[0m[0;34m+[0m[0;34m'fzt_ALrd'[0m[0;34m+[0m[0mstr[0m[0;34m([0m[0mfiles[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m)[0m[0;34m+[0m[0;34m'.fits'[0m[0;34m)[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mfiles[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mprint[0m[0;34m([0m[0mimage[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m.[0m[0mheader[0m[0;34m[[0m[0;34m'FILENAME'[0m[0;34m][0m[0;34m,[0m[0mimage[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m.[0m[0mheader[0m[0;34m[[0m[0;34m'OBJECT'[0m[0;34m][0m[0;34m,[0m[0mimage[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m.[0m[0mheader[0m[0;34m[[0m[0;34m'EXPTIME'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'fits' is not defined
NameError: name 'fits' is not defined

